name: intmacro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - jupyterlab
  - jupyter-book
  - myst-nb
  - sphinx-book-theme
  - pip:
    - ipython
    - sympy
    - scipy
    - plotly
    - nbformat
    - jupyter-client
    - jupyter-core
    - jupyter-server
    - jupyterlab-server
    - notebook
    - voila 